# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a3cfcb97147855f460c1e61c65586654f5456555aa734305f0cc86b189b13cfeb8e7a2c97b1a8988c048085860777db6e570c27aaef8a8bbc623b28851c9985

test:
  secret_key_base: 5a8511b6787f9e587fb79b3da67f085308d2f53346084f74450fa4c483174195a5a3df21d437c092f60c9e3f2ae66603252fa8e8446c35df26366c3d59aec14b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
